# IPS
ip:
  forwarder_from_docker: host.docker.internal
  forwarder_local: 127.0.0.1
  instrument: 192.168.0.112

# PORTS
port:
  forwarder_from_docker: 5000
  forwarder_local: 5000
  instrument: 4001

simulation_script: brunel_basic
