IP = "127.0.0.1"

GUI_PORT = 1337
SPIKE_DISPLAY_PORT = 1338
RECORDING_PORT = 5020

SPIKE_DISPLAY_ADDRESS = '/display_spikes'
GUI_PAR_ADDRESS = '/gui_pars'
GUI_SPIKE_ADDRESS = '/gui_spikes'
RECORDING_ADDRESS = '/record'
