IP = "127.0.0.1"

GUI_PORT = 1337
SPIKE_DISPLAY_PORT = 1338
RECORDING_PORT = 5020

SPIKE_DISPLAY_ADDRESS = '/display_spikes'
GUI_PAR_ADDRESS = '/gui_pars'
GUI_SPIKE_ADDRESS = '/gui_spikes'
GUI_RESET_ADDRESS = '/gui_reset'
GUI_OUTPUT_SETTINGS_ADDRESS = '/gui_output_settings'
GUI_START_ADDRESS = '/gui_start'
GUI_STOP_ADDRESS = '/gui_stop'
RECORDING_ADDRESS = '/record'
