displays:
  spike_display:
    ip: 127.0.0.1
    port: 1338
    address: /spikedisplay/spikes/

---
output:
  server:
    ip: 192.168.33.1
    port: 8080
    route: /spikes

---
sources:
  simulator:
    ip: 192.168.33.1
    port: 8080
    address: /spikes
