# IPS
ip:
  simulator: 192.168.33.10
  output_server: 192.168.1.98
  instrument: 127.0.0.1

# PORTS
port:
  simulator: 8080
  output_server: 8080
  instrument: 5020



#displays:
#  spike_display:
#    ip:
#    port: 1338
#    address: /spikedisplay/spikes/
#
#---
#output:
#  server:
#    ip:
#    port:
#    route: /spikes
#
#---
#sources:
#  simulator:
#    ip:
#    port:
#    address: /spikes
